name: $(Major).$(Minor).$(Build)

variables:
  - group: Secrets
  - name: Major
    value: 1
  - name: Minor
    value: 0
  - name: Build
    value: $[counter('',0)]

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: AzurePowerShell@4
  displayName: Install dependant modules and run InvokeBuild script
  inputs:
    azureSubscription: 'Azure'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location -Path $(Build.SourcesDirectory)
      Install-Module -Name "PSScriptAnalyzer" -RequiredVersion 1.18.3 -Force
      Install-Module -Name "InvokeBuild" -RequiredVersion 5.5.3 -Force
      Install-Module -Name "Pester" -RequiredVersion 4.9.0 -Force
      Invoke-Build
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
